INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")
INSERT INTO projects VALUES ("title", "category", funding_goal, "start_date", "end_date")


INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)
INSERT INTO users VALUES ("name", age)


INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
INSERT INTO pledges VALUES (amount, user_id, project_id)
